# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trials of an Aspirant
email: h.orefice@gmail.com
description: From Engineering to Sociology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.horefice.com" # the base hostname & protocol for your site 
linkedin_username:  horefice
github_username:  horefice

# Build settings
markdown: kramdown
